version: '3'
services:
  php:
    build: ./build/web
    restart: always
    ports:
      - 8080:80
      - 25565:25565
    depends_on:
      - mariadb
    volumes:
      - ./app:/var/www/html
      - ./lib:/var/www/html/lib
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /bin/bash -c "service apache2 start && cd lib/ && composer install && cd .. && service apache2 stop && /usr/sbin/apache2ctl -D FOREGROUND"

  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
        - ./mariadb-data:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data: