version: '3'
services:
  php:
    image: php:8.2-apache
    restart: always
    command: sh /var/www/scripts/modules.sh
    ports:
      - 9000:80
    depends_on:
      - mariadb
    volumes:
      - ./app:/var/www/html
      - ./scripts:/var/www/scripts
    
  mariadb:
    image: mariadb:10.4
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data: