version: '3'
services:
  php:
    image: php:8.2-apache
    restart: always
    ports:
      - 9000:80
    depends_on:
      - mariadb
    volumes:
      - ./app:/var/www/html
      - ./scripts/php:/var/www/html/scripts



  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
        - ./mariadb-data:/var/lib/mysql
        - ./scripts/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --init-file /docker-entrypoint-initdb.d/initial.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data: