FROM debian:bookworm-slim

ENV xms="1G"
ENV xmx="2G"
ENV enablequery="false"
ENV enablercon="false"
ENV enableServerPropertiesFile="false"
ENV rconpassword=""

RUN apt update -y
RUN apt install -y screen openjdk-17-jdk-headless

RUN mkdir /minecraft
WORKDIR /minecraft

ADD https://download.getbukkit.org/spigot/spigot-1.20.2.jar /server.jar

COPY entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh

EXPOSE 25565 25575

ENTRYPOINT ["/entrypoint.sh"]