FROM ubuntu:jammy

ENV xms="1G"
ENV xmx="2G"
ENV enablequery="false"
ENV enablercon="false"
ENV enableServerPropertiesFile="false"
ENV rconpassword=""

RUN apt update -y
RUN apt install -y screen openjdk-8-jdk-headless

RUN mkdir /minecraft
WORKDIR /minecraft

ADD https://piston-data.mojang.com/v1/objects/48820c84cb1ed502cb5b2fe23b8153d5e4fa61c0/server.jar /server.jar

COPY entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh

EXPOSE 25565 25575

ENTRYPOINT ["/entrypoint.sh"]